server:
    port: 8081
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hugojesusmr/MicroserviceSpring.git
          search-paths: condig-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t         
          
   
